version: '2'

services:
  drone-server:
    image: drone/drone:0.8
    ports:
      - 80:80
      - 443:443
      - 9000:9000
    restart: always
    volumes:
      - ./data:/var/lib/drone/
      - ./cert/fullchain.pem:/etc/certs/drone.noledge.tech/server.crt
      - ./cert/privkey.pem:/etc/certs/drone.noledge.tech/server.key
    environment:
      - DRONE_SERVER_CERT=/etc/certs/drone.noledge.tech/server.crt
      - DRONE_SERVER_KEY=/etc/certs/drone.noledge.tech/server.key
      - DRONE_OPEN=true
      - DRONE_HOST=${DRONE_HOST}
      - DRONE_GITHUB=true
      - DRONE_GITHUB_CLIENT=${DRONE_GITHUB_CLIENT}
      - DRONE_GITHUB_SECRET=${DRONE_GITHUB_SECRET}
      - DRONE_SECRET=${DRONE_SECRET}
      - DRONE_LETS_ENCRYPT=true

  drone-agent:
    image: drone/drone:0.5
    command: agent
    restart: always
    depends_on: [ drone-server ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=ws://drone-server:8000/ws/broker
      - DRONE_SECRET=${DRONE_SECRET}
