version: '2'

services:
  drone-server:
    image: drone/drone:0.8
    ports:
      - 80:80
      - 443:443
      - 9000:9000
    restart: always
    volumes:
      - ./data:/var/lib/drone/
      - ./certs/cert.pem:/etc/certs/drone.noledge.tech/cert.pem
      - ./certs/privkey.pem:/etc/certs/drone.noledge.tech/privkey.pem
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=${DRONE_HOST}
      - DRONE_GITHUB=true
      - DRONE_GITHUB_CLIENT=${DRONE_GITHUB_CLIENT}
      - DRONE_GITHUB_SECRET=${DRONE_GITHUB_SECRET}
      - DRONE_SECRET=${DRONE_SECRET}
      - DRONE_SERVER_CERT=/etc/certs/drone.noledge.tech/cert.pem
      - DRONE_SERVER_KEY=/etc/certs/drone.noledge.tech/privkey.pem

  drone-agent:
    image: drone/drone:0.8
    command: agent
    restart: always
    depends_on: [ drone-server ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_HOST=${DRONE_HOST}
      - DRONE_SECRET=${DRONE_SECRET}
      - DRONE_GITHUB=true
      - DRONE_GITHUB_CLIENT=${DRONE_GITHUB_CLIENT}
      - DRONE_GITHUB_SECRET=${DRONE_GITHUB_SECRET}

